import type { Metadata } from "next";
// import { Roboto_Flex } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css"
import "react-toastify/dist/ReactToastify.css";


// const roboto = Roboto_Flex(
//   {
//     subsets: ["latin"],
//     weight: ["400", "500", "600", "700", "800"],
//     style: ["normal"]
//   }
// )

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
export default RootLayout;
